### ISSUE TITLE
pfetch will not delete 

### ISSUE THREAD

**Issue by LordIndra** [dylanaraps/pfetch#102]
I downloaded pfetch through the wget option and was able to delete the master.zip but pfetch will not delete as I get the error of
"E: unable to locate pfetch" 
(I am on Kali Linux) 
![Screenshot_20210210_232258](https://user-images.githubusercontent.com/66719821/107602353-2eba7d80-6bf7-11eb-9159-097f390acd1f.png)

**Comment by LordIndra** [comment]
I was able to delete it with certain command sorry for the disturbance

**Comment by TheThunderGuyS** [comment]
If you've solved your problem, close the issue.
