### ISSUE TITLE
weird "host" section

### ISSUE THREAD

**Issue by Pan00Pernicek** [dylanaraps/pfetch#105]
![Screenshot_20210315_090027](https://user-images.githubusercontent.com/61617356/111121436-ed5a1c80-856c-11eb-8ac5-9900100a9e83.png)
`Type1ProductConfigId` is what is weird, all other fetches dont shows it

**Comment by TheThunderGuyS** [comment]
Likely a hardware-specific issue, as `get_host()` simply reads what's provided by the BIOS to either the Linux kernel or systemd. It can probably be fixed in the loop at line 449, which intends to strip OEM information and bugs like this.

**Comment by Pan00Pernicek** [comment]
Thanks, i will look into it.
