### ISSUE TITLE
Weird text before bold/colored letters on Konsole 

### ISSUE THREAD

**Issue by dnnis** [dylanaraps/pfetch#107]
### Issue
Hello, I am using pfetch on Konsole. I have noticed that before the first output texts ("uptime", "os", "pkgs" etc.) the program is outputting the string "1C". 
Is this some escape code Konsole is not interpreting correctly?

Below I am attaching the image on my screen.

![issue](https://user-images.githubusercontent.com/57800665/113559571-4ff18600-960a-11eb-80b2-bc8d3d91e614.png)

### System
Using Arch Linux, kernel 5.10.25-1-lts with bash. KDE as DE with Konsole as Terminal Emulator.

**Comment by dylanaraps** [comment]
Can you reproduce in other VTE based terminal emulators (GNOME, termite, xfce4-terminal, etc)?

**Comment by dnnis** [comment]
It seems that the issue appears on Konsole only. Xfce4-terminal, Kitty, Alacritty, Gnome Terminal do not seem to have the same bug.

**Comment by TheThunderGuyS** [comment]
I cannot replicate this issue under Konsole 21.08.1
![image](https://user-images.githubusercontent.com/52540509/132543723-3610d40c-7db4-4752-9b09-0aee72c1aa99.png)

**Comment by dylanaraps** [comment]
@TheThunderGuyS Does it still work with ascii enabled?

**Comment by TheThunderGuyS** [comment]
> @TheThunderGuyS Does it still work with ascii enabled?

Yes

**Comment by dylanaraps** [comment]
Closing this unless anyone else with Konsole can reproduce.
