### ISSUE TITLE
Add MSYS_NT-10.0-21354 support.

### ISSUE THREAD

**Issue by UnkindledTwo** [dylanaraps/pfetch#108]
When I build and run pfetch with msys2 I get this error:
```
error: MSYS_NT-10.0-21354 is not currently supported.
error: Open an issue for support to be added.
```

**Comment by dylanaraps** [comment]
Please try: https://github.com/dylanaraps/pfetch/pull/22

Note: There is no ASCII logo in that PR. 

Let me know what works/doesn't.

**Comment by dylanaraps** [comment]
Direct further comments here: https://github.com/dylanaraps/pfetch/issues/108
