### ISSUE TITLE
WM/DE support

### ISSUE THREAD

**Issue by Baitinq** [dylanaraps/pfetch#11]
I think that adding window manager info would be a nice addition.

**Comment by kaewhyes** [comment]
> I think that adding window manager info would be a nice addition.

Maybe Desktop Environments, too?

**Comment by Baitinq** [comment]
Indeed

**Comment by dylanaraps** [comment]
Window manager support is done (For Linux) in #13.

**Comment by dylanaraps** [comment]
Desktop environment support is done in https://github.com/dylanaraps/pfetch/pull/15.

Please test both PRs.

**Comment by kaewhyes** [comment]
Ok, now that I have the time to check out the PRs, here's what I'm noticing.

On the WM PR, the only issue here is that there is no `os` output. Other than that, it seems to be working fine in detecting bspwm.

![wm_pr_image](http://i.salejandro.me/b4Kxc.png)

I gave the DE PR a try, and noticed that there was again no `os` output. There was also no `de` output, which is self-explanatory (Should there be a "none" fallback for cases like this?).

**Comment by dylanaraps** [comment]
It's meant to be `os` and not `distro` (just pushed a fix for this in the documentation). Which DE did you try?

**Comment by kaewhyes** [comment]
> Which DE did you try?

I'm not using a DE.

**Comment by dylanaraps** [comment]
That's working as intended then.

**Comment by Minda1975** [comment]
Hello.Thanks for the neat little tool. But i have the same issue. There is no `wm` output. Here is screenshot:
<img src="https://i.ibb.co/GPRrjbc/2019-09-30-201824-423x131-scrot.png" alt="2019-09-30-201824-423x131-scrot" border="0">

By the way, i'm not using a DE, only wm, xmonad.

**Comment by dylanaraps** [comment]
Did you enable it in `PF_INFO`?

**Comment by Minda1975** [comment]
> Did you enable it in `PF_INFO`?

I'm sorry. It's my fault. Now everything works.

**Comment by dylanaraps** [comment]
Done. :+1:
