### ISSUE TITLE
wm displaying on MacOS

### ISSUE THREAD

**Issue by drewauff** [dylanaraps/pfetch#111]
runnning ZSH on Catalina 10.5.7.

no matter what I do, I cannot get wm show.

**Comment by TheThunderGuyS** [comment]
pfetch will simply return if it encounters a Mac OS system (the same way it would if no WM is installed on Linux), because there is no choice of window manager.

**Comment by drewauff** [comment]
Im running Amethyst WM so that should show, I have also tried with other WM's with no success.
