### ISSUE TITLE
Support for CelOS

### ISSUE THREAD

**Issue by whyadamsalt** [dylanaraps/pfetch#123]
It'd be nice if there was support for CelOS
![CelOS](https://user-images.githubusercontent.com/75907419/125109787-b1c6fd80-e0db-11eb-82f0-867f212f60da.png)

**Comment by dylanaraps** [comment]
It would be nice if you could put effort into your issue.

**Comment by whyadamsalt** [comment]
output of /etc/os-release:
```
NAME="CelOS"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=celos
ID_LIKE=debian
PRETTY_NAME="CelOS 1 GNU/Linux"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-pol>
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

Package managers: Apt/dpkg & Flatpak

**Comment by MrVeink** [comment]
What is this CelOS? I couldn't really find anything about it

**Comment by whyadamsalt** [comment]
> What is this CelOS? I couldn't really find anything about it

It's a Linux Distribution I am currently working on.
https://celos.cobweb-aclevo.org

**Comment by MrVeink** [comment]
I suggest this issue being closed?
