### ISSUE TITLE
I edited some of your poorly written text

### ISSUE THREAD

**Issue by Raytle** [dylanaraps/pfetch#125]
I suggest you consider using some or all of the following verbiage after you edit my comments in bold...

### Project Goal
Whenever feasible, I strove to create a simple yet robust information tool **[What is an "information tool"? That phrase is way, way, way too vague]** in POSIX sh using features built into the language itself.

### Well-Documented Code
I have worked hard to meticulously document the code in the hopes that the documentation for this project will act as a learning resource, not merely for POSIX sh, but also as simple information detection **["simple information detection"? That phrase makes no sense to me]** across various different operating systems, including, but not limited to, Linux, Windows, Mac, and even FreeBSD.

Don't take my word for it, instead watch [this YouTube video](https://youtu.be/aP0hf_QaLE8?t=135) for merely a couple of seconds.

### Questions, Comments, and Suggestions are Welcome
If you have any questions, comments, or suggestions about this project I would appreciate it if you would open an issue. I have created four types of issues: Bugs, Feature Requests, Suggestions, and Clarification Needed. Want a new feature? Feel free to ask. Don't understand the source code or see a more elegant way to implement a solution? Let me know what you think. I fear I am suffering from "project myopia"; that is I have become so close to the project that I am unable to [see the forest from the trees](https://en.wiktionary.org/wiki/see_the_forest_for_the_trees#:~:text=(idiomatic)%20To%20discern%20an%20overall,the%20forest%20for%20the%20trees.).

# The following is poorly written
The goal of this project is to implement a simple system information tool in POSIX sh using features built into the language itself (where possible).

The source code is highly documented and I hope it will act as a learning resource for POSIX sh and simple information detection across various different operating systems.

If anything in the source code is unclear or is lacking in its explanation, open an issue. Sometimes you get too close to something and you fail to see the "bigger picture"!

**Comment by system32uwu** [comment]
Why don't you make a PR including the changes you want to implement?

**Comment by Raytle** [comment]
I have never made a pull request in my life. I'm not an engineer. I've never used pfetch nor do I intend to use it. I'm not even sure what pfetch does. I simply contributed some editorial changes after glancing at [Pfetch: Everyone's Favourite System Info Tool](https://www.youtube.com/watch?v=aP0hf_QaLE8).

**Comment by system32uwu** [comment]
I'm not an engineer either, and you definitely don't need to be one in order to propose grammar / content / spelling / punctuation changes to the README (which is not even source code). Pfetch is open source, meaning, if you don't like something, or would prefer it in a different way, you can actually propose those changes with a [pull request](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request). You can also open the [README](https://github.com/dylanaraps/pfetch/blob/master/README.md) file online and click the pencil icon (which on hover says "Fork this project and edit the file")

How don't you know what pfetch does? You linked a video that explains what pfetch does in less than 30s...

**Comment by Raytle** [comment]
> I'm not an engineer either, and you definitely don't need to be one in order to propose grammar / content / spelling / punctuation changes to the README (which is not even source code). 

Thanks for explaining that to me. I was unaware of that approach of suggesting changes on Github.. By the way, that's a run-on sentence... ; )


> Pfetch is open source, meaning, if you don't like something, or would prefer it in a different way, you can actually propose those changes with a pull request.

Thanks, I know what open source means. Sure. It's extremely common for people to do what you indicated, but no, that is not what open source means: not a little, not at all. This is what open source means... https://en.wikipedia.org/wiki/Open_source.

> You can also open the README file online and click the pencil icon (which on hover says "Fork this project and edit the file")

Thanks for explaining that to me too.

> How don't you know what pfetch does? You linked a video that explains what pfetch does in less than 30s...

After about 5 to 10 seconds of watching the video I lost interest pfetch. I doubt I need pfetch. It looks like what I call "a tool for techies." I'm not a techie.

**Comment by yuri-norwood** [comment]
@Raytle the wording of the README is subjective, if you disagree with the wording, or anything about the project for that matter, open a pull request. That is how changes are made, reviewed, and if approved, that's how suggestions make their way into the project.

Debating on the definition of what open source is or isn't, being rude to members of the community, and demanding changes to the project without putting the bare minimum amount of effort in, that is not the way things are done around here. Not in the project, not on GitHub, and certainly not if you want your changes to be approved.

The beauty of collaborative projects like pfetch is that anyone can contribute changes, regardless of skill level or background. You don't have to be an engineer or "techie" as you call it. You clearly are capable of writing markdown, you're using it right now as you write a doubtlessly rude reply, and if you open a pull request it may even be merged.

**Comment by Xeno-Hypster** [comment]
This is the most needlessly rude and asinine issue I've seen from someone who doesn't even know what the tool is and is self-admitting not the target audience. Get this language prescriptivism outta here, holy shit.

**Comment by TheThunderGuyS** [comment]
These suggestions give off a very condescending, disrespectful and passive-aggressive attitude. It's unnecessary to say something like "I edited some of your poorly written text" or (implied to be from dylanaraps' perspective) "I fear I am suffering from 'project myopia'" (which also disrespects the reader's intelligence by listing a definition). In prior discussion you have even admitted to not understanding the purpose of this project, please do not suggest things if you don't know what you're doing.

Furthermore, most of the suggestions are effectively invalid and pointless. The entire text you listed above is needlessly verbose and confusing, and speaks from the first-person and past-tense when not appropriate. You have simply taken the existing text, given it some adjectives found in a thesauruses and added sentences that attempt to advertise the program as opposed to detailing its purpose. The purpose of a README file is to list what a program is and why it is that way, not to persuade the reader to install it.

You have also failed to detail why the existing README is "poorly written". As far as I'm concerned, it gets the point across in a few short and concise sentences, ideal for a well-written README.

**Comment by dylanaraps** [comment]
I do not have any plans to rewrite or restructure this README for the moment. 

Thanks for the issue @Raytle.

**Comment by system32uwu** [comment]
lmao
