### ISSUE TITLE
I suggest you add a screencast similar to Flameshot preview

### ISSUE THREAD

**Issue by Raytle** [dylanaraps/pfetch#126]
I suggest you add a screencast similar to [Flameshot preview](https://github.com/flameshot-org/flameshot#preview).

If a [picture is worth a thousand words](https://en.wiktionary.org/wiki/a_picture_is_worth_a_thousand_words), well, remember videos are usually at least ten pictures per second.

**Comment by dylanaraps** [comment]
Thanks for the suggestion but I don't think this is necessary.

**Comment by Raytle** [comment]
Thanks for letting me know. I appreciate that.
