### ISSUE TITLE
PF_COLOR=0 is not doing anything

### ISSUE THREAD

**Issue by Soundtoxin** [dylanaraps/pfetch#134]
I'm running Guix System and I can't seem to get the color to go away. I tried both `export PF_COLOR=0` followed by `pfetch` and `PF_COLOR=0 pfetch`, but I still get colored output.
I'm running version 0.7.0 of pfetch according to `pfetch --version` and the version number of the guix package.

**Comment by Soundtoxin** [comment]
`PF_COL1=9 PF_COL2=9 PF_COL3=9 pfetch` works for me to get all the text white, but I don't see an option to recolor the ascii logo.

**Comment by dylanaraps** [comment]
I cannot reproduce with master.

**Comment by dylanaraps** [comment]
```
-> PF_COLOR=0 pfetch
    ___       dylan@desert
   (.. |      os     KISS Linux
   (<> |      host   x86_64
  / __  \     kernel 5.12.6
 ( /  \ /|    uptime 5m
_/\ __)/_)    pkgs   112
\/-____\/     memory 878M / 15976M
```

**Comment by Soundtoxin** [comment]
![2021-08-17-231428_grim](https://user-images.githubusercontent.com/3146494/129835994-2948afcb-dc27-4462-97e6-3589ad8b1628.png)

The guix package says it pulls from commit `e18a0959ab98b963744755ec4687e59dc11db3c5` in case that helps.

**Comment by Soundtoxin** [comment]
I updated to latest commit and it works now! Sorry for the trouble. I guess maybe this feature wasn't in the version I had before.

![2021-08-17-232259_grim](https://user-images.githubusercontent.com/3146494/129836574-a3ace8b3-d951-4a04-ac4a-396532376b91.png)
