### ISSUE TITLE
pfetch -v line 318: /sys/firmware/devicetree/base/model: No such file or directory

### ISSUE THREAD

**Issue by Soundtoxin** [dylanaraps/pfetch#137]
I ran `pfetch -v` to see if it would print the version and I noticed it prints this error.
`line 318: /sys/firmware/devicetree/base/model: No such file or directory`
It also prints out pfetch normally anyway (see #135), getting out two normal lines, then displaying the error, then continuing to print the pfetch, thus cutting between the pfetch in the middle and looking rather ugly.

What is this option supposed to do? I don't get that error with `--version`. Is it verbose? Is it showing an error that's always there but normally hidden?

**Comment by Crestwave** [comment]
> Is it verbose? Is it showing an error that's always there but normally hidden?

Yes, it's verbose. It prevents the discarding of stderr.
