### ISSUE TITLE
Where is the configuration file for pfetch located? Or do I have to create it myself?

### ISSUE THREAD

**Issue by amarakon** [dylanaraps/pfetch#143]

**Comment by yuri-norwood** [comment]
You can set `PF_SOURCE` in your `.profile` to any file you like. If it's a valid shell script, `pfetch` will use any variables set in that scrip, e.g. `PF_ASCII="openbsd", as it's configuration.

**Comment by TheThunderGuyS** [comment]
See `README.md`
> `pfetch` is configured through environment variables.

Close the issue if you have resolved your problem.
