### ISSUE TITLE
if the guix package manager is present pfetch identifies the system as gnu guix 

### ISSUE THREAD

**Issue by M0M097** [dylanaraps/pfetch#144]
I run Slackware and have the guix package manager installed. Neofetch recognizes my OS as Slackware, but pfetch thinks I'm running gnu guix:

➜  pfetch git:(master) pfetch
|.__          __.|    me@localhost.localdomain
|__ \        / __|    os     Guix System
   \ \      / /       host   SATELLITE PRO A30-D PT381E-00C00YGR
    \ \    / /        kernel 5.14.0
     \ \  / /         uptime 1h 57m
      \ \/ /          pkgs   19
       \__/           memory 1856M / 15941M

**Comment by dylanaraps** [comment]
Does this occur in master?

**Comment by M0M097** [comment]
yes

**Comment by dylanaraps** [comment]
This should be fixed. Let me know if it still occurs.
