### ISSUE TITLE
extra delimiter symbol when it is not default

### ISSUE THREAD

**Issue by Delected** [dylanaraps/pfetch#145]
hey there, thanks for this amazing project!

i just noticed a little visual bug that i can reproduce in any terminal emulator.

when setting a delimiter using `export PF_SEP`, an extra one is printed after the palette (see below for screenshot)

![2021-09-01-182808_576x220_scrot](https://user-images.githubusercontent.com/58377193/131754182-a668dcf3-aeb8-400e-9763-5ddc95ba597f.png)

```
export PF_SEP=' ~ '
export PF_ALIGN=4
export PF_COL1=3
export PF_COL2=3
export PF_INFO='os wm host pkgs palette'
```

**Comment by Delected** [comment]
could be said that this is a duplicate of #82, but is there going to be a fix for this?

**Comment by dylanaraps** [comment]
Yes. I am just very busy right now.

**Comment by Delected** [comment]
> 
> 
> Yes. I am just very busy right now.

absolutely no problem! if i knew posix i would love to pr, but unfortunately i do not. take your time, it's not urgent

**Comment by Delected** [comment]
that was fast lmao.. thanks a ton!
