### ISSUE TITLE
How do I install pfetch on OpenBSD?

### ISSUE THREAD

**Issue by amarakon** [dylanaraps/pfetch#151]
When I do doas pkg_add pfetch, it says Can't find pfetch.

**Comment by dylanaraps** [comment]
It's a self contained script. Just download it from GitHub of your OS or distribution does not provide a package.

**Comment by yuri-norwood** [comment]
Hello future googlers:

```sh
git clone https://github.com/dylanaraps/pfetch
cd pfetch/
doas make install
cd ..
rm -rf ./pfetch
```

**Comment by TheThunderGuyS** [comment]
No operating system provides pfetch in their repositories unlike neofetch.

You can just run `curl -LO https://raw.githubusercontent.com/dylanaraps/pfetch/master/pfetch` and move the script to any directory you desire (such as /usr/bin).

**Comment by xeruf** [comment]
sudo curl -L https://raw.githubusercontent.com/dylanaraps/pfetch/master/pfetch -o /usr/bin/pfetch && sudo chmod +x /usr/bin/pfetch

This makes it ready to use immediately :) maybe this could be added to the README for quick copying

**Comment by unsubtract** [comment]
> ```
> sudo curl -L https://raw.githubusercontent.com/dylanaraps/pfetch/master/pfetch -o /usr/bin/pfetch && sudo chmod +x /usr/bin/pfetch
> ```
> 
> This makes it ready to use immediately :) maybe this could be added to the README for quick copying

OpenBSD does not provide `sudo(8)` with a default install. It uses `doas(1)` instead.

**Comment by maklamj** [comment]
> No operating system provides pfetch in their repositories unlike neofetch.
> 
> You can just run `curl -LO https://raw.githubusercontent.com/dylanaraps/pfetch/master/pfetch` and move the script to any directory you desire (such as /usr/bin).

https://pkgs.org/search/?q=pfetch
FreeBSD, NetBSD, Void Linux }official x3, Arch unofficial & AUR.

**Comment by maklamj** [comment]
> No operating system provides pfetch in their repositories unlike neofetch.
> 
> You can just run `curl -LO https://raw.githubusercontent.com/dylanaraps/pfetch/master/pfetch` and move the script to any directory you desire (such as /usr/bin).

https://pkgs.org/search/?q=pfetch
FreeBSD, NetBSD, Void Linux }official.
