### ISSUE TITLE
How do I configure pfetch? I'm a newbie and can't figure out how to configure it.

### ISSUE THREAD

**Issue by midnightxd** [dylanaraps/pfetch#153]

**Comment by dylanaraps** [comment]
https://github.com/dylanaraps/pfetch#configuration
https://en.wikipedia.org/wiki/Environment_variable

**Comment by midnightxd** [comment]
So I will have to set them one-by-one?
Can't I just set them all together and edit them using a text editor like vim or nano whenever I want to.

**Comment by yuri-norwood** [comment]
See my notes under #149, pfetch *can* be configured with a text file, e.g. `.pfetchrc`, but you have to set it up yourself.

**Comment by midnightxd** [comment]
Oh figured it out.  Thanks!
