### ISSUE TITLE
Thoughts on switching to The ISC License

### ISSUE THREAD

**Issue by TheThunderGuyS** [dylanaraps/pfetch#154]
[The ISC License](https://choosealicense.com/licenses/isc/) is 100% compatible with The MIT License and The BSD 2-Clause "Simplified" License. It omits language that was made obsolete by the [Berne Convention](https://en.wikipedia.org/wiki/Berne_Convention) and thus has a smaller file size. OpenBSD has already adopted this as the preferred license for new code, as opposed to the MIT and BSD licenses used prior.

Due to being functionally identical to the MIT license currently in use, changing the license is not a problem as all code used (regardless of author) is licened under the exact same terms.

**Comment by dylanaraps** [comment]
This seems unnecessary for an existing project. Will consider it for future projects though.

Thanks for the issue.

**Comment by ghost** [comment]
The Free Software Foundation seems to recommend against the ISC License as they deem its language too vague.
