### ISSUE TITLE
showing incorrect memory usage

### ISSUE THREAD

**Issue by wael444** [dylanaraps/pfetch#156]
this might be similar to https://github.com/dylanaraps/pfetch/issues/90, but i'm not sure what the problem is here,
pfetch shows
![image](https://user-images.githubusercontent.com/47404953/134550725-a195beb5-4310-4844-b29f-cd71f4f88d18.png)

```(MemAvailable - MemTotal) / 1024``` shows ```4059```

htop shows
![image](https://user-images.githubusercontent.com/47404953/134550910-7638d1c9-f8c0-436f-972f-8bc21ea0074f.png)

what is going on here?

note: these were all executed at the exact same time

**Comment by dylanaraps** [comment]
Please try master.

**Comment by wael444** [comment]
> Please try master.

pfetch now shows the correct memory usage as shown by 
```(MemAvailable - MemTotal) / 1024```, ~~though htop shows 100 mb less~~
though what is actually the correct memory usage calculation? is it just Avail - Total or is there something else to it?

**Comment by dylanaraps** [comment]
There is no right answer. You can read more about it here: https://github.com/KittyKatt/screenFetch/issues/386#issuecomment-249312716
