### ISSUE TITLE
Next release ETA?

### ISSUE THREAD

**Issue by Soundtoxin** [dylanaraps/pfetch#162]
Will there be another release soon? It looks like it's been quite a while. I imagine distro packagers would rather package a release than a specific commit from master, but doing so would mean losing out on many changes.

**Comment by dylanaraps** [comment]
I will make a release in the Winter (when I have ample time).

**Comment by Soundtoxin** [comment]
Hey, we're most of the way through February now. Just a reminder in case you forgot about this.

**Comment by Soundtoxin** [comment]
Another friendly bump. I see there haven't been commits in a while. You're probably busy.
