### ISSUE TITLE
where are the config

### ISSUE THREAD

**Issue by MaybeAnonymous** [dylanaraps/pfetch#166]
how do i customize this, i can't find the config file

**Comment by yuri-norwood** [comment]
There isn't one, pfetch is configured with environment variables. You can set these in your `~/.profile`, e.g. `export PF_ASCII="OpenBSD"`. Check out the read me for a full list of these variables.

If you want to have a separate file, you can make one yourself using the `PF_SOURCE` variable, if you set it to a file path, that file will be treated a shell script and included by pfetch.

For example, in your `~/.profile`:

```sh
export PF_SOURCE="${HOME}/.config/pfetch/pfetchrc" # you can use a different file if you want
```

In your "pfetchrc" (or whatever you choose to call it:

```sh
PF_ASCII="OpenBSD" # note that there is no export key word here
```
