### ISSUE TITLE
makefile?

### ISSUE THREAD

**Issue by kiedtl** [dylanaraps/pfetch#17]
Can we add a makefile for easy installation/uninstallation?

```
$ sudo make install # or, sudo make uninstall
```

**Comment by kaewhyes** [comment]
There is no need for a `Makefile`, its just a shell script.

**Comment by dylanaraps** [comment]
`pfetch` is just a single file that you can copy/paste somewhere in your `$PATH`. There are no other files or directories to copy or create. A `Makefile` would just end up being a wrapper around `cp` or `install`/`rm`.
