### ISSUE TITLE
Call for Android testers

### ISSUE THREAD

**Issue by dylanaraps** [dylanaraps/pfetch#19]
Send me the full outputs of the following commands:

- `getprop ro.build.version.release` (*needed for OS identification*).

Notes:

- `neofetch` detects Android by checking for the existence of two directories:
    - `[ -d /system/app/ ] && [ -d /system/priv-app ]`
- Does this work on your Android device?

**Comment by kaewhyes** [comment]
> run: `[ -d /system/app/ ] && [ -d /system/priv-app ] && echo hi`

Just ran it, `hi` was returned.

**Comment by Benjamin-Davies** [comment]
Android 9 Samsung J3
1st command: 9
2nd command: no output, succeeded

**Comment by dylanaraps** [comment]
Try the latest master, Android support should be done.

**Comment by Benjamin-Davies** [comment]
![](https://i.imgur.com/VE4kThY.jpg)
Thanks so much.
