### ISSUE TITLE
Capitalize first letter of entries?

### ISSUE THREAD

**Issue by Zsargul** [dylanaraps/pfetch#201]
Is it possible to configure the program to capitalize the first letter of each displayed entry, (`Os: `, `Kernel: `, `Host: `), the way they are in neofetch? I know this is an incredibly tiny detail but it just slightly annoys me.

**Comment by mag4no10** [comment]
You can change it in your /usr/bin/pfetch, for example for "shell" to "Shell" would be in in lane 898
