### ISSUE TITLE
EndeavourOS ascii art misaligned

### ISSUE THREAD

**Issue by dnvnxg** [dylanaraps/pfetch#209]
![image](https://user-images.githubusercontent.com/47253847/222042785-4e0a0d59-f2bd-4b1b-a271-457e82ba6756.png)
The screenshot shows the problem

**Comment by Gobidev** [comment]
This project seems to be more or less abandoned, as the maintainer has been inactive for ~over 2 years~ over 1 year. You can checkout [my rewrite of pfetch in Rust](https://github.com/Gobidev/pfetch-rs) that runs faster than this version and has the EndeavourOS logo fixed.

**Comment by Un1q32** [comment]
> the maintainer has been inactive for over 2 years

over one year

**Comment by dnvnxg** [comment]
Thank you for the heads up
