### ISSUE TITLE
endeavour os ascii art not showing correctly

### ISSUE THREAD

**Issue by mzakyr42** [dylanaraps/pfetch#210]
this is the output of the pfetch command :
```
                mzakir@localhost     /\
    //  \\      os     EndeavourOS Linux
   //    \ \    host   20F5S1F700 ThinkPad X260
 / /     _) )   kernel 6.2.10-arch1-1
/_/___-- __-    uptime 1h 5m
 /____--        pkgs   997
                memory 2363M / 7691M

```
why the user and hostname cut the ascii art

**Comment by mzakyr42** [comment]
idk how to fix this

**Comment by Gobidev** [comment]
You can use pfetch-rs instead: https://github.com/Gobidev/pfetch-rs, it is fixed there. You could also copy the endeavorOS logo from there into the shell script, that will fix it.

**Comment by mzakyr42** [comment]
i switched to arch lol

**Comment by Un1q32** [comment]
based
