### ISSUE TITLE
Can't open another command after pfetch in gnome-terminal

### ISSUE THREAD

**Issue by Darkpepito** [dylanaraps/pfetch#211]
Hi,
I use the gnome-terminal to execute the following command:
`pfetch && zsh`
The output is:
`pfetch     show system information
pfetch -d  show stderr (debug mode)
pfetch     show version information
`
It acts like `pfetch --help`
What can I do ?

**Comment by Darkpepito** [comment]
I tried in terminator and it works, i don't know why it doesn't work in gnome-terminal

**Comment by Darkpepito** [comment]
Fixed, I just added pfetch to .zshrc.

**Comment by Un1q32** [comment]
&& is a shell thing, since gnome-terminal isn't running the command you give through a shell, `&& zsh` gets passed as an argument to the pfetch command, rather then running pfetch, then zsh.  The proper way to do these kinds of things is always to add them to the .zshrc as you did.
