### ISSUE TITLE
Logo for AlmaLinux OS

### ISSUE THREAD

**Issue by Minda1975** [dylanaraps/pfetch#212]
Hello. Thank you for your project. I have a request. Could you include in your project support for AlmaLinux OS logo?

Here is the [link](https://almalinux.org/) for official website.

**Comment by Gobidev** [comment]
The maintainer of this project has been inactive for a while, but you can check out [my rewrite of pfetch in Rust](https://github.com/Gobidev/pfetch-rs) which does include an Alma Linux logo as well as several other improvements.

The logo format is also compatible with this project if you prefer the POSIX version.

It looks like this:
![image](https://github.com/dylanaraps/pfetch/assets/50576978/572eaad6-0875-4640-8c28-feb02295d161)

**Comment by Minda1975** [comment]
> The maintainer of this project has been inactive for a while, but you can check out [my rewrite of pfetch in Rust](https://github.com/Gobidev/pfetch-rs) which does include an Alma Linux logo as well as several other improvements.
> 
> The logo format is also compatible with this project if you prefer the POSIX version.

Thank you for the link. I am using your project now. Everything works great. I close this issue.

 [![Screenshot-from-2023-05-12-15-51-39.png](https://i.postimg.cc/pdF4n1Wx/Screenshot-from-2023-05-12-15-51-39.png)](https://postimg.cc/FfhDMpkn)
