### ISSUE TITLE
Packages for AUR/Deb/etc...?

### ISSUE THREAD

**Issue by GitSquared** [dylanaraps/pfetch#25]
Would be great to see this packaged for some Linux distros' repos.
ArchLinux's AUR is a good place to start.

**Comment by dylanaraps** [comment]
`pfetch` is already in the AUR, Haiku ports and FreeBSD ports.

This isn't up to me. It's up to users to package and maintain packages for their Linux distributions or Operating systems. Besides, `pfetch` is a single file you can drop anywhere and execute. There aren't any dependencies or additional files to install.

Thanks for opening this issue.
