### ISSUE TITLE
Disk Usage

### ISSUE THREAD

**Issue by KittyKatt** [dylanaraps/pfetch#27]
From experience, I know that this isn't the easiest thing in the world with the differences between `df` outputs, but I think it might be worth getting `Full disk space used across all mounted partitions` / `Full disk space available across all mounted partitions`. This would only take up a single extra line.

Ideas on implementation? Or not interested?

**Comment by dylanaraps** [comment]
I've tackled and implemented this in `neofetch` (*see `get_disk()`*) and there are quite a few edge cases between `df` versions (*as you've mentioned*). This shouldn't be too difficult to add though I'm unsure if it's a good fit for `pfetch`.

I'll have a crack at it regardless. :+1:

**Comment by KittyKatt** [comment]
Being unfit is a good argument, seeing as how the purpose of pfetch is to be as simple as possible. If you need an extra set of hands, I'm more than happy to tackle some pieces of it.

**Comment by dylanaraps** [comment]
Here's an implementation following only `/`: https://github.com/dylanaraps/pfetch/pull/28

This can be expanded to include any number of disks, mount points or locations. What needs to be done to implemented the behavior you desire above? 

(*Ignore my nonsense attempts to remove an unrelated commit =P*)

**Comment by dylanaraps** [comment]
To test: 

- Modify the environment variable `PF_INFO` to include `disk` (*See the `README` for more information*).
