### ISSUE TITLE
Possible to force distro ascii art?

### ISSUE THREAD

**Issue by nixnoob** [dylanaraps/pfetch#32]
Hi! I really love pfetch, it's smooth, slick, and fast! I'm just having one minor dilemma with it, and that's that I am using [anarchy linux](https://www.anarchylinux.org/), which is an Arch-based distribution. However it is not seeming to be recognized by pfetch (or the ascii art just simply isn't in the code), but either way it simply prints back the default Linux penguin (https://pastebin.com/Q0d3uDxK), which quite frankly is ugly. I'd like to, if possible, force pfetch to return the Arch ascii art instead, which I figure is possible since neofetch can do so. Is this doable? if so, how?

Thanks in advance!

**Comment by dylanaraps** [comment]
`PF_ASCII=arch pfetch`. This can also be set in your `.profile` or `.shellrc` file.
