### ISSUE TITLE
OpenWRT support?

### ISSUE THREAD

**Issue by Strykar** [dylanaraps/pfetch#37]
What would it take to enable OpenWRT support? How can I help?
See https://gist.github.com/Strykar/6de68967b9c0a382ef0002806dc6460e

**Comment by dylanaraps** [comment]
Added support for `opkg`, all that's missing now is a logo.

**Comment by Strykar** [comment]
@dylanaraps The logo is already in OpenWRT, it's rather wide unlike most distros. If the width works, it can be displayed on openwrt by `cat /etc/banner`.
Here's what it looks like - https://gist.github.com/Strykar/4adb5d38df483ea1f61e2b59150a950f

What's the max width for ascii logos in pfetch?

**Comment by dylanaraps** [comment]
There's no set width in the code but it's better if the logo sticks to a "squareish" size. This size or a bit bigger is preferred. How wide would the output be if the `/etc/banner` was used? I'd say the absolute upper barrier would be 80 columns for obvious reasons.

```sh
-> pfetch
    ___       goldie@KISS
   (.· |      os     KISS Linux
   (<> |      host   80MK Lenovo YOGA 900-13ISK
  / __  \     kernel 5.4.0-rc6-cat
 ( /  \ /|    uptime 3m
_/\ __)/_)    pkgs   158
\/-____\/     memory 671M / 7940M
```

**Comment by Strykar** [comment]
The banner is exactly 54 columns `-----------------------------------------------------`
That's just the OpenWRT banner, the text still has to wrap around it.
