### ISSUE TITLE
Environment variables not working (Ubuntu 19.10)

### ISSUE THREAD

**Issue by vaskark** [dylanaraps/pfetch#41]
I must be doing something wrong. I've listed the env variables in my .zshrc file but they are not being recognized. Example:

`PF_INFO="ascii title os host kernel shell wm uptime pkgs memory"
`

`shell` and `wm` are not showing up.

Can someone point out what I'm doing wrong?
Thanks.

**Comment by dylanaraps** [comment]
The variable must be exported. `export PF_INFO="bla bla"`.
