### ISSUE TITLE
OpenBSD: ASCII art cut off and improper kernel detection

### ISSUE THREAD

**Issue by mitchweaver** [dylanaraps/pfetch#46]
![image](http://0x0.st/iAOa.png)

OpenBSD 6.6-current, using latest commit

**Comment by dylanaraps** [comment]
Try the latest commit. Kernel will once again be hidden (as OS name shows it).

**Comment by mitchweaver** [comment]
@dylanaraps 
![img](http://0x0.st/iAOM.png)

**Comment by dylanaraps** [comment]
Interesting!

**Comment by dylanaraps** [comment]
I'm working on a fix. :+1:

**Comment by mitchweaver** [comment]
@dylanaraps Latest commit fixed it.

I have some other changes I'd like to run by you:

1. Would you like to display whether the OS is `OpenBSD 6.6` or `OpenBSD 6.6-current`? There is an easy sysctl variable to check.

2. Would you like to display `ThinkPad X200` rather than `LENOVO 746963`? I'm not sure if this is a bug or desired behaviour

**Comment by dylanaraps** [comment]
1. Sure. Send the command my way.
2. This is dependent on `sysctl`, know the right comman?

**Comment by mitchweaver** [comment]
@dylanaraps 

I'd PR but it'd be easier for you to just format it how you would prefer

1. This is how I would write it:
```sh
        OpenBSD)
            # Detect if '-release' or '-current'
            case $(sysctl kern.version) in
                *current*) current=-current
            esac
            distro="$os $kernel${current}"
        ;;
```

2. use `hw.version` instead of `.model`

```sh
        OpenBSD)
            host=$(sysctl -n hw.version)
        ;;
```

**Comment by dylanaraps** [comment]
Full output of: `sysctl kern.version`?

**Comment by mitchweaver** [comment]
It's pretty messy, that's why I used the case statement

```sh
~ sysctl kern.version
kern.version=OpenBSD 6.6-current (GENERIC.MP) #40: Sun Mar  8 20:17:34 MDT 2020
    deraadt@amd64.openbsd.org:/usr/src/sys/arch/amd64/compile/GENERIC.MP

~
```

**Comment by dylanaraps** [comment]
Made both changes, thanks.
