### ISSUE TITLE
Latest update produces strange results

### ISSUE THREAD

**Issue by vaskark** [dylanaraps/pfetch#48]
```
         _    osUbuntu 19.10
     ---(_)   ke5.5.8-custom
 _/  ---  \   up1d 3h 21m
(_) |   |     pk2956
  \  --- _/   shzsh:
     ---(_)   wmsowm sowm sowm sowm

```
The wm property has always done this for me. Here's what I have in .zshrc:

```
# pfetch
export PF_INFO="ascii os kernel uptime pkgs shell wm"
export PF_SEP=":"
export PF_COL1=3
export PF_COL2=2
```

**Comment by dylanaraps** [comment]
Is this via version 0.6.0?

**Comment by vaskark** [comment]
Nope. 0.7.0. Just updated.

**Comment by dylanaraps** [comment]
Fixed the WM issues.

**Comment by dylanaraps** [comment]
Output of: `echo $PF_ALIGN`?

**Comment by vaskark** [comment]
`echo $PF_ALIGN` produces nothing. I tried using that in my .zshrc but wasn't sure what the choices were. Assumed left, right, center but it didn't produce any effect.

**Comment by dylanaraps** [comment]
Try the latest commit. :+1:

**Comment by vaskark** [comment]
Works great :)
