### ISSUE TITLE
Solus?

### ISSUE THREAD

**Issue by Scupake** [dylanaraps/pfetch#63]
Solus support please.

**Comment by dylanaraps** [comment]
Just need a logo.

**Comment by Scupake** [comment]
I'll try to make one, should I keep the circle, or just the boat thing?

**Comment by Scupake** [comment]
I made this:
![image](https://user-images.githubusercontent.com/61241021/85392119-046e5f80-b543-11ea-97c8-6d36d02ec11d.png)

**Comment by Scotty-Trees** [comment]
Solus implementation when? @Scupake looks great!

**Comment by ressonix** [comment]
Here's another one:

```
       ,_
       I~
       |\
      /|.\
     / || \
   ,'  |'  \
.-'.-==|/_--'
`--'-------'
```

**Comment by ressonix** [comment]
If you want to go ahead and add this yourselves, you can edit the `pfetch` file and add this in the appropriate section:

```bash
        ([Ss]olus*)
            read_ascii 4 <<-EOF
				${c4}       ,_
				${c4}       I~
				${c4}       |\\
				${c4}      /|.\\
				${c4}     / || \\
				${c4}   ,'  |'  \\
				${c4}.-'.-==|/_--'
				${c4} --'-------'
			EOF
        ;;
        ```
