### ISSUE TITLE
Colors are different on darwin

### ISSUE THREAD

**Issue by mendelmaleh** [dylanaraps/pfetch#66]
Why would the title and info colors be different on mac?

![image](https://user-images.githubusercontent.com/31070530/88283130-da7e9900-ccb8-11ea-8137-9d5924b7bda0.png)

**Comment by dylanaraps** [comment]
Text colors are derived from ASCII colors unless the `PF_COL[1-4]` (`PF_COL1`, `PF_COL2`, etc)  environment variables are set..
