### ISSUE TITLE
Call for IRIX testers

### ISSUE THREAD

**Issue by dylanaraps** [dylanaraps/pfetch#8]
Send me the full outputs of the following commands:

- `LC_ALL=POSIX ps -o etime= -p 1` (*needed for uptime*).
    - A better way of getting uptime in seconds would be nice!
- `versions -b` (*needed for package count*).
- `pmem` (*needed for memory*).

**Comment by bitmappergit** [comment]
Will do, just gotta boot up my Octane.

**Comment by dylanaraps** [comment]
IRIX is done.
