### ISSUE TITLE
Palette attribute has a colon after it

### ISSUE THREAD

**Issue by vaskark** [dylanaraps/pfetch#82]
I'm getting an extra colon after the palette atribute. Example:

```
os:      Ubuntu 20.10
kernel:  5.9.2-custom
uptime:  2h
shell:   zsh
wm:      bspwm
memory:  1820M / 7848M

(palette colours here)
             :
```

I'm using:

```
export PF_INFO="os kernel uptime shell wm memory palette"
export PF_SEP=":"
export PF_COL1=2
export PF_COL2=4
```
Thanks.

Edit: pfetch-git (latest) 0.7.0

**Comment by anntnzrb** [comment]
yes, this is a thing; if you disable `PF_SEP=":"` it will be gone.

**Comment by vaskark** [comment]
Many thanks.

**Comment by anntnzrb** [comment]
@dylanaraps unsure if this could be fixed, because it's currently not possible to use a separator without this being a little uglish.
