### ISSUE TITLE
Support to comply with NO_COLOR?

### ISSUE THREAD

**Issue by TheThunderGuyS** [dylanaraps/pfetch#89]
The [NO_COLOR](https://no-color.org/) organization is proposing a standard for all programs that emmit ANSI color codes, where if the NO_COLOR enviroment variable is present the program emmits no colored output. This is because some people might not want color and not want to set settings for each program (but still want support for color in the terminal, explained in their FAQ).

Will there be support for this in pfetch?

**Comment by dylanaraps** [comment]
Done. I've added a new option called `PF_COLOR` which allows for control over this. It is set to `1` by default. Set it to `0` and no colors will appear in the output.
