### ISSUE TITLE
Shows incorrect usage of RAM

### ISSUE THREAD

**Issue by uchihamalolan** [dylanaraps/pfetch#90]
I ran `pfetch` and `top` to compare RAM consumption data and `pfetch` is very much off the mark.

Result from running `top`:

> MiB Mem :   1970.8 total,   1551.6 free,    106.5 used,    312.6 buff/cache

Result from running `pfetch`:
```
       /\         os     Arch Linux
     /\   \       host   VirtualBox 1.2
    /      \      kernel 5.9.8-arch1-1
   /   ,,   \     uptime 4h 33m
  /   |  |  -\    pkgs   256
 /_-''    ''-_\   memory 250M / 1970M

```

**Comment by dylanaraps** [comment]
How are you certain that pfetch is wrong here and top isn't incorrect? pfetch calculates memory in the same way as neofetch, screenfetch, conky, htop, archey4, etc, etc. If there is indeed a bug I'm happy to look into it, we just need to figure out where the correctness lies.

See: 

- https://github.com/KittyKatt/screenFetch/issues/386#issuecomment-249312716
- https://github.com/dylanaraps/neofetch/blob/master/neofetch#L2562-L2588
- https://github.com/dylanaraps/neofetch/wiki/Frequently-Asked-Questions#linux-is-neofetchs-memory-output-correct
- https://github.com/KittyKatt/screenFetch/blob/master/screenfetch-dev#L1804-L1820 
    - (seem to have swapped to parsing `free` output but code is still there)
- https://github.com/dylanaraps/pfetch/blob/master/pfetch#L666-L695
- https://github.com/brndnmtthws/conky/issues/130
- https://github.com/HorlogeSkynet/archey4/commit/90975d4ee31d3826c0a6a192b0c7248054eec9d5
- etc

Anyway, I'll do some digging.

**Comment by dylanaraps** [comment]
All of this being said, on kernels post 2014 ([https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=34e431b0ae398fc54ea69ff85ec700722c9da773](34e431b0ae398fc54ea69ff85ec700722c9da773))  neofetch/pfetch will use `MemAvailable` for used memory instead of calculating the value.

**Comment by dylanaraps** [comment]
Related: https://github.com/htop-dev/htop/issues/281

Author of issue claims the used memory allocation is inaccurate stating that MemAvailable is what should be used

**Comment by uchihamalolan** [comment]
> All of this being said, on kernels post 2014 ([34e431b0ae398fc54ea69ff85ec700722c9da773](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=34e431b0ae398fc54ea69ff85ec700722c9da773)) neofetch/pfetch will use `MemAvailable` for used memory instead of calculating the value. Only when this field is absent will the used memory calculation be done.

I ran both pfetch and neofetch. but the mem consumed info there differs.
could you check?

> pfetch:      memory 431M / 3917M
> neofetch:  Memory: 225MiB / 3917MiB

**Comment by uchihamalolan** [comment]
I manually calculated with both formulas (from `/proc/meminfo`).
when I use the formula with `MemAvailable` the `pfetch` information is correct. The output from `neofetch` that I shared in the previous comment is result of using the older formula, which gives much lower memory consumption (I guess it would seem a small difference when memory consumption is around 2-3 Gigs). same could be said for `htop`

**Comment by dylanaraps** [comment]
Are you trying with latest master for both pfetch and neofetch? The MemAvailable addition is new for both (and not yet in a release).

**Comment by uchihamalolan** [comment]
@dylanaraps 
Yes you're correct, `neofetch` code does not have `MemAvailable` addition. I installed `neofetch` using pacman. (Meanwhile pfetch is built from source, hence latest code was available) That explains it then I guess.

**Comment by dylanaraps** [comment]
Yeah. Will make new releases of both shortly. Closing this as it's been solved. :)
